### ISSUE TITLE
B: Group Communication/Custom Group Reminder Emails Exception

### ISSUE THREAD

**Issue by nateh777** [KingdomFirst/RockAssemblies#136]
# Expected Behavior

For it to work and not generate an exception.

# Current Behavior

It is generating an exception on a 15.1 server. I believe it is related to just being built on a previous version that does not reference the correct related DLL. Needs to be confirmed on a controlled server, as I noticed the exception on a client's server.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. Run Job on 15.1
2. Generates Exception.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: 15.1
* Database Version: Microsoft SQL Azure (RTM) - 12.0.2000.8 Jul 17 2023 18:40:52 Copyright (C) 2022 Microsoft Corporation
* Windows Version:

## Failure Logs

Please include any relevant log snippets or files here.

> (9/24/2023 4:00 PM) Method not found: 'Ical.Net.Interfaces.DataTypes.IPeriod...
> 
> Exception Date
> 9/24/2023 4:00 PM
> Description
> Method not found: 'Ical.Net.Interfaces.DataTypes.IPeriod Ical.Net.DataTypes.Occurrence.get_Period()'.
> 
> Details
> This list shows the complete exception hierarchy with a full call-stack trace. The top-level exception is listed first, and subsequent entries provide more specific detail about the origin of the error.
> 
> Id	Exception Type	Source	Description	 
> 331387	System.MissingMethodException	rocks.kfs.CustomGroupCommunication	Method not found: 'Ical.Net.Interfaces.DataTypes.IPeriod Ical.Net.DataTypes.Occurrence.get_Period()'.	
>    at rocks.kfs.CustomGroupCommunication.Jobs.CustomMeetingGroupReminder.Execute(IJobExecutionContext context)
>    at Quartz.Core.JobRunShell.Run()

**Comment by guymaness2** [comment]
Issue should have been closed with merge of #139
